language: node_js
node_js:
   - "node"

services:
  - docker

sudo: required

before_install:
    - docker pull crossbario/crossbar
    - docker run --rm -d -it -p 8888:8888 -v ${PWD}:/node crossbario/crossbar
    - sleep 5

after_script: "./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha --report lcovonly -- --exit --require babel-core/register -R spec 'test/!(wampy-crossbar)-test.js' && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"

notifications:
  email:
    recipients:
      - KSDaemon@ya.ru
      - andrew.bakal@gmail.com
    on_success: change
    on_failure: always