language: node_js
node_js:
   - "node"

before_install:
    - export PATH=$HOME/.local/bin:$PATH
    - pip install --user crossbar

before_script:
    - sh -c 'crossbar start &'

after_script: "./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"

notifications:
  email:
    recipients:
      - KSDaemon@ya.ru
      - andrew.bakal@gmail.com
    on_success: change
    on_failure: always

